name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --pre -r .requirements.txt

      - name: Test with pytest
        run: |
          pytest
        env:
          PYTHONPATH: /home/runner/work/gks-common/gks-common/
